# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSXVAuQ4T_QQ25gCbYiejf1ieg-fXJ0D
"""

!pip install mongomock
!pip install pymongo

import mongomock
from pymongo.errors import PyMongoError

print("iniciando")

print("iniciando")

import mongomock
from pymongo.errors import PyMongoError
print("=========================================================")
print(" INICIANDO O LABORATÓRIO PRÁTICO DE BACK-END")
print("=========================================================")
cliente = mongomock.MongoClient()
db = cliente['loja_banco']
produtos = db['produtos']
print(" [CONEXÃO]: Simulador do MongoDB iniciado com sucesso!")
novo_item = {
 "nome": "Teclado Mecânico Gamer",
 "preco": 189.90,
 "estoque": 25
}
retorno = produtos.insert_one(novo_item)
print(f" [CREATE]: Item salvo! O banco carimbou o ID único: {retorno.inserted_id}")
print("\n--- [READ]: CONSULTANDO OS ITENS DA GAVETA ---")
todos_produtos = produtos.find()
for p in todos_produtos:
  print(f" Produto: {p['nome']} | Preço: R$ {p['preco']} | Estoque: {p['estoque']}")
filtro_busca = {"nome": "Teclado Mecânico Gamer"}
nova_informacao = {"$set": {"preco": 219.90}}
produtos.update_one(filtro_busca, nova_informacao)
print("\n [UPDATE]: O preço do Teclado foi reajustado no banco!")
produto_conferido = produtos.find_one(filtro_busca)
print(f" [CONFERÊNCIA]: Novo preço verificado no banco: R$ {produto_conferido['preco']}")
produtos.create_index([("preco", 1)])
print("\n [OTIMIZAÇÃO]: Índice de preços criado! Consultas agora são instantâneas.")
print("\n [TRANSAÇÃO]: Iniciando uma simulação de venda segura...")
print("\n [TRANSAÇÃO]: Iniciando uma simulação de venda segura...")
produtos.insert_one({"nome": "Mouse Sem Fio", "preco": 50.0, "estoque": 5})
print(" [AVISO]: O BLOCO DE TRANSAÇÃO foi pulado, pois mongomock não suporta sessões.\nPara usar transações, é necessário um servidor MongoDB real.")
print("\n=========================================================")
print(" FIM DO LABORATÓRIO: TODOS OS BLOCOS FUNCIONANDO!")
print("=========================================================")